import * as ImageManipulator from 'expo-image-manipulator';
import * as FileSystem from 'expo-file-system/legacy';

export interface SelectedImage {
  uri: string;
  width: number;
  height: number;
  mimeType: string;
  fileSize: number;
}

export async function processImage(uri: string): Promise<SelectedImage> {
  try {
    // We cannot reliably use ImageManipulator on the original URI if we don't know dimensions, 
    // but Expo ImagePicker gives us dimensions. However, we should be robust.
    // Instead of querying dimensions manually, we can pass no actions to manipulateAsync just to get info.
    // Or we can assume ImagePicker gives the dimensions, but wait, processImage(uri: string) 
    // only takes a URI. Let's just use ImageManipulator to get the raw info first.
    // A trick to get image info is to do a manipulateAsync with no actions.
    const initialResult = await ImageManipulator.manipulateAsync(uri, []);
    
    let { width, height } = initialResult;
    
    // Step 1: Resize if needed
    const actions: ImageManipulator.Action[] = [];
    if (width > 2048 || height > 2048) {
      if (width >= height) {
        actions.push({ resize: { width: 2048 } });
      } else {
        actions.push({ resize: { height: 2048 } });
      }
    }
    
    // Step 2: Compress
    const finalResult = await ImageManipulator.manipulateAsync(uri, actions, {
      compress: 0.75,
      format: ImageManipulator.SaveFormat.WEBP,
    });
    
    // Step 3: Save to specific temp file location
    const tempUri = FileSystem.cacheDirectory + "card_" + Date.now() + ".webp";
    await FileSystem.copyAsync({
      from: finalResult.uri,
      to: tempUri
    });
    
    // Clean up the intermediate file generated by ImageManipulator
    try {
      const intermediateInfo = await FileSystem.getInfoAsync(finalResult.uri);
      if (intermediateInfo.exists) {
        await FileSystem.deleteAsync(finalResult.uri, { idempotent: true });
      }
    } catch (e) {
      console.warn("Failed to clean up intermediate image file:", e);
    }

    // Step 4: Get final file size
    const fileInfo = await FileSystem.getInfoAsync(tempUri);
    
    if (!fileInfo.exists) {
      throw new Error("Failed to save processed image.");
    }

    return {
      uri: tempUri,
      width: finalResult.width,
      height: finalResult.height,
      mimeType: "image/webp",
      fileSize: fileInfo.size || 0
    };
    
  } catch (error) {
    console.error("Image processing error:", error);
    throw new Error("Failed to process image. Please try again.");
  }
}

export interface CropRect {
  originX: number;
  originY: number;
  width: number;
  height: number;
}

export async function cropImage(uri: string, crop: CropRect): Promise<SelectedImage> {
  try {
    const actions: ImageManipulator.Action[] = [{ crop }];
    
    const finalResult = await ImageManipulator.manipulateAsync(uri, actions, {
      compress: 0.75,
      format: ImageManipulator.SaveFormat.WEBP,
    });
    
    const tempUri = FileSystem.cacheDirectory + "card_crop_" + Date.now() + ".webp";
    await FileSystem.copyAsync({
      from: finalResult.uri,
      to: tempUri
    });
    
    try {
      const intermediateInfo = await FileSystem.getInfoAsync(finalResult.uri);
      if (intermediateInfo.exists) {
        await FileSystem.deleteAsync(finalResult.uri, { idempotent: true });
      }
    } catch (e) {
      console.warn("Failed to clean up intermediate image file:", e);
    }
    
    const fileInfo = await FileSystem.getInfoAsync(tempUri);
    if (!fileInfo.exists) {
      throw new Error("Failed to save cropped image.");
    }
    
    return {
      uri: tempUri,
      width: finalResult.width,
      height: finalResult.height,
      mimeType: "image/webp",
      fileSize: fileInfo.size || 0
    };
  } catch (error) {
    console.error("Image cropping error:", error);
    throw new Error("Failed to crop image.");
  }
}
